apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-argo-aplication
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/alexandrubyte/kube_learn.git
    targetRevision: HEAD
    path: dev

  destination:
    server: https://kubenetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true