apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: webs-app
  replicas: 2 # tells deployment to run 3 pods matching the template
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver-alex
        image: alexandrubyte/kube_learn
        ports:
        - containerPort: 80