apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  selector:
    matchLabels:
      app: web-app
  replicas: 20 # tells deployment to run 3 pods matching the template
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: alexandrubyte/webserver
        ports:
        - containerPort: 80